CREATE TEMPORARY TABLE t1 (i INT, t TEXT) USING memoryam;

INSERT INTO t1 VALUES (1, 'hello');
INSERT INTO t1 VALUES (2, 'world');

SELECT * FROM t1;

UPDATE t1 SET t = 'foo' WHERE i = 2;

SELECT * FROM t1;

UPDATE t1 SET t = 'bar', i = 3 WHERE i = 1;

SELECT * FROM t1;

DROP TABLE t1;
